### PR TITLE
Add correct_escapes=true to radiusd.conf

### PR DESCRIPTION
**Pull request by sts**
Currently the regex escape sequences of policy.d/filters doesn't work with 1lab packages on jessie. This enables correct_escapes=true in radius.d conf.

The following shipped filter doesn't work, with the shipped puppet configuration:

```
#  reject double dots
#  e.g. "user@site..com"
if (&User-Name =~ /\.\./ ) {
...
```

### CODE REVIEW

**Comment by djjudas21** [comment]
Thanks, this looks useful. Would it be possible to set this as a configurable parameter in `init.pp` and have the default set to `false`? I'm unhappy to push out a change of behaviour to production, it's bound to break someone's system (including mine :wink:)

**Comment by sts** [comment]
This would break the default configuration of `policy.d/filter`, `filter_username` supplied with freeradius 3.

**Comment by djjudas21** [comment]
OK then. I'll accept a default of `true` provided there's a note in the `README` that tells people to be careful if they have legacy config.

Another contributor is currently working on some breaking changes so we'll roll these all up in a new major release - thanks.

**Comment by sts** [comment]
Parameter has been added, since I don't know what else will be in the release, I haven't updated the README, I'll leave that up to you.

Regarding other major changes, are you referring to issue #46 ?

**Comment by djjudas21** [comment]
The other changes haven't been sent in yet but the conversation is in #51. I'm happy to accept this change now so I'll merge it, and I'll write up some scary words for the `README` when I roll the release. Thanks!

**Pull request merged**
