### PR TITLE
Fix huntgroups when there is more than one condition

### PR DESCRIPTION
**Pull request by amateo**
In huntgroups, when there is more than one condition for a huntgroup, each condition should be indicated in one huntgroup line, instead of separated by commas.

In this PR I have also deleted the huntgroup template that is not needed anymore since PR#96.

### CODE REVIEW

**Comment by djjudas21** [comment]
I would prefer if the template can remain as a file, rather than a variable embedded in Puppet code

**Comment by djjudas21** [comment]
Great, thanks. Is there any change in the format that the user must specify?

**Comment by amateo** [comment]
No, I think. `$conditions` could be a string or an array, as before.

**Comment by djjudas21** [comment]
OK great, I'm happy with this. Will merge.

**Pull request merged**
