### PR TITLE
Add support for different ldap attribute for NT password hash

### PR DESCRIPTION
**Pull request by dabelenda**

### CODE REVIEW

**Comment by djjudas21** [comment]
This looks good, thanks. Can you add documentation for the new parameter to `README.md` please?

**Comment by djjudas21** [comment]
Hey, any progress on this? I either want to complete this or delete it. Thanks.

**Comment by amateo** [comment]
You already could this with the ```update``` parameter I added in a previous PR.

**Comment by djjudas21** [comment]
Thanks @amateo , I'll close this dupe then

**Pull request closed without merging**
