### PR TITLE
add support for EL9 (RedHat, Rocky and AlmaLinux)

### PR DESCRIPTION
**Pull request by sircubbi**
This PR will add support for EL9 and also include AlmaLinux in the process.

Please note that CI is currently failing (which I fixed in PR #181). I can rebase once that other PR got merged.

### CODE REVIEW

**Comment by nward** [comment]
Haha - beat me to this one as well!

Does Alma have the same paths for FreeRADIUS as CentOS/RHEL/Rocky? I've not used Alma.

**Comment by sircubbi** [comment]
> Does Alma have the same paths for FreeRADIUS as CentOS/RHEL/Rocky? I've not used Alma.

It actually does. Only difference between the different flavours are more or less the copyrighted artwork and logos from RedHat.

**Comment by nward** [comment]
Have you had a look at #178? I think the same issue exists in EL9

**Comment by sircubbi** [comment]
> Have you had a look at #178? I think the same issue exists in EL9

Yes, I saw that. However it is not necessary in EL9, since bootstrap is not called there. Comparing the systemd-Unitfiles I see that `ExecStartPre=-/bin/sh /etc/raddb/certs/bootstrap` is no longer present on EL9, most likely related to this changelog-entry:
```
* Wed Mar 10 2021 Robbie Harwood <rharwood@redhat.com> - 3.0.21-11
- Disable automatic bootstrap
```

I just rolled out a new freeradius-configuration on Rocky9 yesterday and had no issues with this puppet module (except the missing guess for the version of the freeradius-package, which is fixed with this PR).

**Comment by nward** [comment]
> Please note that CI is currently failing (which I fixed in PR #181). I can rebase once that other PR got merged.

Go for gold

**Comment by sircubbi** [comment]
> > Please note that CI is currently failing (which I fixed in PR #181). I can rebase once that other PR got merged.
> Go for gold

Thanks, rebase is done and the CI now actually goes green ;)

**Review by nward — APPROVED** [review]

**Comment by djjudas21** [comment]
Thanks @nward and @sircubbi for your efforts on this :+1:

**Pull request merged**
