### PR TITLE
Individual SNMP trap enabling

### PR DESCRIPTION
**Pull request by deligatedgeek**
Added a template for trigger.conf and 4 new parameters for freeradius class

- $snmp_traps_enable - Whether to actual trap and not just echo commands
- $snmp_traps_community - The SNMP community string/shared secret of the trap destination
- $snmp_traps_dest - The IP address of the trap destination
- $snmp_traps - And array of trap names, if empty it is populated with all trap names, if a list of traps is supplied then those are enabled.

There are no dependencies between parameters to allow full configuration of file and checking before enabling traps

### CODE REVIEW

**Comment by deligatedgeek** [comment]
@nward A clean start on the trigger.conf trap configuration.
Not sure why this is failing tests, but the code does work when testing in my environment

**Comment by deligatedgeek** [comment]
Does anyone why know why checks which are seeming unrelated to my changes are failing, I forked the last commit that passed so I don't know what's going on.

**Comment by djjudas21** [comment]
The tests are also failing in the same way on the latest commit in `main`, so this isn't you, this is the tests. Looks like some incorrectly specified test data.

Are you happy that this change is complete, and working?

**Comment by deligatedgeek** [comment]
@djjudas21  Im happy this is completed and working.

**Comment by djjudas21** [comment]
I've hada quick look, and I'm happy to merge if you can add some basic documentation to [README.md](https://github.com/djjudas21/puppet-freeradius?tab=readme-ov-file#freeradius-1) to include the new parameters, the expected values, etc. Thanks.

@nward is there anything you want to add before we merge?

**Pull request merged**
